// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBcKE3QZraG7fl1Se9BQkBBpzpbr4bMI',
    appId: '1:438238634887:web:b3f81acc9463a5ad266922',
    messagingSenderId: '438238634887',
    projectId: 'coolfirebas',
    authDomain: 'coolfirebas.firebaseapp.com',
    storageBucket: 'coolfirebas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDvvyMeXsAa5vOqRuOh6eFyK8c-AC0UU',
    appId: '1:438238634887:android:7107424fb3e39de2266922',
    messagingSenderId: '438238634887',
    projectId: 'coolfirebas',
    storageBucket: 'coolfirebas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-Qdvg6CUdpNKzDngn3PlrnQ89FVTTWY',
    appId: '1:438238634887:ios:0b7fba4a76775e06266922',
    messagingSenderId: '438238634887',
    projectId: 'coolfirebas',
    storageBucket: 'coolfirebas.appspot.com',
    iosClientId: '438238634887-e10qdp9n297qephcfffq9ukjvaue5vou.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsignupfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-Qdvg6CUdpNKzDngn3PlrnQ89FVTTWY',
    appId: '1:438238634887:ios:0b7fba4a76775e06266922',
    messagingSenderId: '438238634887',
    projectId: 'coolfirebas',
    storageBucket: 'coolfirebas.appspot.com',
    iosClientId: '438238634887-e10qdp9n297qephcfffq9ukjvaue5vou.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginsignupfirebase',
  );
}
